### ISSUE TITLE
TRSS-Plugin依赖安装失败

### ISSUE THREAD

**Issue by BMYY12138** [TimeRainStarSky/TRSS_Yunzai#3]
- 正在安装插件：TRSS-Plugin

正克隆到 'TRSS-Plugin'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 0
接收对象中: 100% (12/12), 504.00 KiB | 557.00 KiB/s, 完成.

- 插件安装完成

- 正在安装依赖

:: 正在同步软件包数据库...
 core 已经是最新版本
 extra 已经是最新版本
 community 已经是最新版本
 archlinuxcn          1950.5 KiB  6.03 MiB/s 00:00 [####################] 100% arch4edu 已经是最新版本
警告：python-poetry-1.2.2-1 已经为最新 -- 跳过
警告：gcc-12.2.0-1 已经为最新 -- 跳过
:: 正在进行全面系统更新...
 今日无事可做

- 正在安装 图片修复

正克隆到 'Real-ESRGAN'...
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 120 (delta 15), reused 72 (delta 4), pack-reused 0
接收对象中: 100% (120/120), 4.33 MiB | 816.00 KiB/s, 完成.
处理 delta 中: 100% (15/15), 完成.
Writing to /root/TRSS_Yunzai/home/.config/pip/pip.conf
Installing dependencies from lock file

Package operations: 17 installs, 0 updates, 0 removals

  • Installing torch (1.12.1)
  • Installing werkzeug (2.2.2)
  • Installing addict (2.4.0)
  • Installing filterpy (1.4.5): Failed

  CalledProcessError

  Command '['/root/TRSS_Yunzai/home/.cache/pypoetry/virtualenvs/real-esrgan-wlmxhNEZ-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/root/TRSS_Yunzai/home/.cache/pypoetry/virtualenvs/real-esrgan-wlmxhNEZ-py3.10', '--no-deps', '/root/TRSS_Yunzai/home/.cache/pypoetry/artifacts/93/c3/be/664d91d5e6cb5c7cd9b90181b900c0e5ee47e56f916b983f5c00e829ad/filterpy-1.4.5.zip']' returned non-zero exit status 1.

  at /usr/lib/python3.10/subprocess.py:526 in run
       522│             # We don't call process.wait() as .__exit__ does that for us.
       523│             raise
       524│         retcode = process.poll()
       525│         if check and retcode:
    →  526│             raise CalledProcessError(retcode, process.args,
       527│                                      output=stdout, stderr=stderr)
       528│     return CompletedProcess(process.args, retcode, stdout, stderr)
       529│
       530│

The following error occurred when trying to handle this error:

  EnvCommandError

  Command ['/root/TRSS_Yunzai/home/.cache/pypoetry/virtualenvs/real-esrgan-wlmxhNEZ-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/root/TRSS_Yunzai/home/.cache/pypoetry/virtualenvs/real-esrgan-wlmxhNEZ-py3.10', '--no-deps', '/root/TRSS_Yunzai/home/.cache/pypoetry/artifacts/93/c3/be/664d91d5e6cb5c7cd9b90181b900c0e5ee47e56f916b983f5c00e829ad/filterpy-1.4.5.zip'] errored with the following return code 1, and output:
  Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple
  Processing /root/TRSS_Yunzai/home/.cache/pypoetry/artifacts/93/c3/be/664d91d5e6cb5c7cd9b90181b900c0e5ee47e56f916b983f5c00e829ad/filterpy-1.4.5.zip
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    error: subprocess-exited-with-error

    × pip subprocess to install build dependencies did not run successfully.
    │ exit code: 1
    ╰─> [10 lines of output]
        Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple
        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda0bd1afb0>: Failed to establish a new connection: [Errno 111] 拒绝连接')': /simple/setuptools/
        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda0bd1ba00>: Failed to establish a new connection: [Errno 111] 拒绝连接')': /pypi/web/simple/setuptools/
        WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda0bd1bc70>: Failed to establish a new connection: [Errno 111] 拒绝连接')': /pypi/web/simple/setuptools/
        WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda0bd1be20>: Failed to establish a new connection: [Errno 111] 拒绝连接')': /pypi/web/simple/setuptools/
        WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda0bd1bfd0>: Failed to establish a new connection: [Errno 111] 拒绝连接')': /pypi/web/simple/setuptools/
        WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fda0bd74220>: Failed to establish a new connection: [Errno 111] 拒绝连接')': /pypi/web/simple/setuptools/
        ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
        ERROR: No matching distribution found for setuptools>=40.8.0
        WARNING: There was an error checking the latest version of pip.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.

  at /usr/lib/python3.10/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│
      1478│         return decode(output)
      1479│
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:

  PoetryException

  Failed to install /root/TRSS_Yunzai/home/.cache/pypoetry/artifacts/93/c3/be/664d91d5e6cb5c7cd9b90181b900c0e5ee47e56f916b983f5c00e829ad/filterpy-1.4.5.zip

  at /usr/lib/python3.10/site-packages/poetry/utils/pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│

  • Installing future (0.18.2)
  • Installing lmdb (1.3.0)
  • Installing numba (0.56.3)
  • Installing opencv-python (4.6.0.66)
  • Installing pyyaml (6.0)
  • Installing scikit-image (0.19.3)
  • Installing tb-nightly (2.11.0a20221021)
  • Installing torchvision (0.13.1)
  • Installing tqdm (4.64.1)
  • Installing yapf (0.32.0)

! 依赖安装失败

  按任意键返回

**Comment by TimeRainStarSky** [comment]
网络问题
