### ISSUE TITLE
请问能不能在docker 日志里看到机器人日志？

### ISSUE THREAD

**Issue by thz-hub** [TimeRainStarSky/TRSS_Yunzai#6]
请问能不能在docker 日志里看到机器人日志？我安装完成后日志是空白。

**Comment by ghost** [comment]
> 请问能不能在docker 日志里看到机器人日志？我安装完成后日志是空白。

你可以试试把install-docker.sh里面的 `--log-driver none` 删除掉就可以。具体步骤如下
1.从仓库下载install-docker.sh到本地
2.按照如上先修改保存
3.打开bash命令行运行./install-docker.sh

**Comment by TimeRainStarSky** [comment]
有人反馈日志占用存储空间太多，所以删了，要的可以自己改配置
