### ISSUE TITLE
websocket只监听外网ipv6端口，无法监听外网ipv4端口

### ISSUE THREAD

**Issue by Aqr-K** [TimeRainStarSky/TRSS_Yunzai#7]
您好，我在搭建过程中发现不管是allbot还是单独yunzai的脚本，用docker版正常启动后，websocket只监听ipv6端口，没有开启监听外网ipv4端口，服务器因为没有ipv6地址无法使用websocket。
我试过改过配置文件里comwechat配置的  noserver:true  为  host参数的主机ip，用netstat查了一下，还是不起作用，在网上和群里找了四五天了实在是找不到解决方法了
想问一下，这个脚本能否改动成websocket同时监听外网ipv4？如果可以，怎么改啊？
还有个小问题，这个脚本能否联动得了comwechat linux版？如果可以要改哪些参数啊？

**Comment by Aqr-K** [comment]
> 您好，我在搭建过程中发现不管是allbot还是单独yunzai的脚本，用docker版正常启动后，websocket只监听ipv6端口，没有开启监听外网ipv4端口，服务器因为没有ipv6地址无法使用websocket。 我试过改过配置文件里的comwechat配置里的 noserver:true 为 host参数的主机ip，用netstat查了一下，还是不起作用，在网上和群里找了四五天了实在是找不到解决方法了 想问一下，这个脚本能否改动成websocket同时监听外网ipv4？如果可以，怎么改啊？ 还有个小问题，这个脚本能否联动得了comwechat linux版？如果可以要改哪些参数啊？

**Comment by TimeRainStarSky** [comment]
1. 本来就监听IPv4，你说不能证据在哪？
2. ComWeChat没有Linux版

**Comment by Aqr-K** [comment]
@TimeRainStarSky 
您好
这是我正常用trss-allbot搭建的，
它是不知道为什么搭建出来很奇怪，这是原生安装好后，除了端口其他都没改过东西的，不改端口其实也测不到v4，我设置的是10808端口，但是测不到有v4的监听，只有v6的，连本地的127.0.0.1都没有
然后就是ComWeChat的linux版，可能是我表达的不到位，其实你的库里也fork了，就是那个linux用wine配置的ComWeChat，你库里的项目名是docker-ComWechat，我想了解一下这个脚本理论上能不能支持的了wine启动的ComWeChat
谢谢
![b0c9e8a2412965def19b3787812d81b](https://github.com/TimeRainStarSky/TRSS_Yunzai/assets/95741669/919a2e81-db3f-4d8b-aa3d-79f0bc71c49e)

![db0b19325c8bea6af7fb9598cdc6277](https://github.com/TimeRainStarSky/TRSS_Yunzai/assets/95741669/8aa05a9b-53c0-443c-9973-b274d6ea845f)

![66e4debd65569b601aa3ef843cf99cc](https://github.com/TimeRainStarSky/TRSS_Yunzai/assets/95741669/d67b6818-a78c-4a56-8e8b-c948bc9eb07e)

**Comment by Aqr-K** [comment]
你要说他有v4吧，websocket没有监听到，只有是redis监听的v4；你要说它没v4吧，redis又已经监听到本地的127.0.0.1了
单测10808端口确实只显示v6
我是docker搭建，给的是host网络环境，那些显示占用的端口是其他服务的，就算用bridge模式的网络也是一样测不出v4

**Comment by TimeRainStarSky** [comment]
docker-ComWechat早试过了没用

**Comment by TimeRainStarSky** [comment]
Docker 网络隔离需要端口转发，改了端口当然连不上，netstat 不准，用 curl 127.0.0.1:10808

**Comment by Aqr-K** [comment]
您好，
bridge模式下需要端口转发，我一开始的时候设置了转发端口了。用netstat测，不管是默认的宿主机还是容器里都测不出来，
所以我才去用host模式的host模式共享主机IP与端口，结果也是一样；用netstat直接在宿主机上测，一样是测不到v4的，
用你说curl 127.0.0.1:10808在宿主机上测现在倒是测出来了，
但我现在的问题其实是我现在的服务器只有v4地址没有v6的，我数据库是linux系统的，结果它v4是只监听127.0.01的，我能不能把v6监听的ws://[::]:10808，给改成v4的，我想给它做前后端分离，找了几天，我实在是找不到修改的方法了

**Comment by TimeRainStarSky** [comment]
> 您好， bridge模式下需要端口转发，我一开始的时候设置了转发端口了。用netstat测，不管是默认的宿主机还是容器里都测不出来， 所以我才去用host模式的host模式共享主机IP与端口，结果也是一样；用netstat直接在宿主机上测，一样是测不到v4的， 用你说curl 127.0.0.1:10808在宿主机上测现在倒是测出来了， 但我现在的问题其实是我现在的服务器只有v4地址没有v6的，我数据库是linux系统的，结果它v4是只监听127.0.01的，我能不能把v6监听的ws://[::]:10808，给改成v4的，我想给它做前后端分离，找了几天，我实在是找不到修改的方法了

都说了 netstat 不准，IPv4 是有监听的

**Comment by Aqr-K** [comment]
听你的意思，是不是公网的v4也有监听？只是启动日志里没显示是吧？

**Comment by TimeRainStarSky** [comment]
> 听你的意思，是不是公网的v4也有监听？只是启动日志里没显示是吧？

废话，日志里又没写仅限 IPv6，而且都说了用 curl 测，还有啥好问的

**Comment by TimeRainStarSky** [comment]
反正不可能是 IPv4 没监听的问题，说了半天都是废话

## 避免 xy-problem

+ 参考地址: http://xyproblem.info/

`XY Problem` 表示
1. 提问者想要解决 **原问题 X** ，且觉得解决了 **引申问题 Y** 就能解决 **X** 问题
2. ~~提问者对外提出了解决 **Y** 的的请求~~
3. 回答者帮助提问者解决 **Y** 问题。（浪费了回答者和提问者双方的时间）

> `然而, 最终 Y 问题可能并不是 X 问题的一个合适的解决方法`

因此， 提问者要避免创造这样的修罗场, 需要学会在问题之初就准确描述自己的根本问题。 [学会描述问题](https://github.com/tangx/Stop-Ask-Questions-The-Stupid-Ways#学会描述问题)
